/* eslint-disable import/no-cycle */

import React, { Suspense } from 'react';

const Box = React.lazy(() => import('./layout-elements/box'));
const Container = React.lazy(() => import('./layout-elements/container'));
const Paper = React.lazy(() => import('./layout-elements/paper'));
const Image = React.lazy(() => import('./media-elements/image'));
const ImagePopup = React.lazy(() => import('./media-elements/image-popup'));
const YoutubeVideo = React.lazy(() => import('./media-elements/youtube-video'));
const YoutubeVideoPopup = React.lazy(() => import('./media-elements/youtube-video-popup'));
const Typograhpy = React.lazy(() => import('./text-elements/typograhpy'));
const BasicForm = React.lazy(() => import('./basic-form'));
const NotFound = React.lazy(() => import('../not-found'));

const Element = ({ name, data }) => {
  // TODO: The key can be generated by firebase
  // TODO: The key is used to track the rendering and later to trigger FB Pixel Events
  switch (name) {
    case 'box':
      return <Box data={data} />;
    case 'container':
      return <Container data={data} />;
    case 'paper':
      return <Paper data={data} />;
    case 'typograhpy':
      return <Typograhpy data={data} />;
    case 'image':
      return <Image data={data} />;
    case 'image-popup':
      return <ImagePopup data={data} />;
    case 'youtube-video':
      return <YoutubeVideo data={data} />;
    case 'youtube-video-popup':
      return <YoutubeVideoPopup data={data} />;
    case 'basic-form':
      return <BasicForm data={data} />;
    default:
      return <NotFound />;
  }
};

const Elements = ({ elements }) => {
  return (
    <Suspense fallback={<></>}>
      {elements &&
        elements.map(el => {
          const id = Math.random()
            .toString(36)
            .substring(2, 15); // + Math.random().toString(36).substring(2, 15);keId;

          return <Element key={id} name={el.name} data={el.data} />;
        })}
    </Suspense>
  );
};

export default Elements;
